### ISSUE TITLE
Example of JenkinsFile

### ISSUE THREAD

**Issue by Ramon-Balaguer** [aaronjwhiteside/pipeline-github#1]
Can you give a complete example of jenkinsfile?

**Comment by Ramon-Balaguer** [comment]
i try:

pipeline {
	agent any
	stages {
		stage ('Build'){		
			steps {
				pullRequest['title'] = 'Updated title'

**Comment by aaronjwhiteside** [comment]
Could you please open this issue on the official GitHub repo, https://github.com/jenkinsci/pipeline-github-plugin/

**Comment by Ramon-Balaguer** [comment]
Ok!

Thank you!
